apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource  # Native metrics
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods  # custom metrics
      pods:
        metrics:
          name: active_http_requests
        target:
          type: AverageValue
          averageValue: "100"