apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: product-catalog-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       product-catalog
  updatePolicy:
    updateMode: "Auto"  # Options: "Off", "Initial", "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"  # Applies to all containers 
      minAllowed:
        cpu: "100m"
        memory: "256Mi"
      maxAllowed:
        cpu: "1"
        memory: "2Gi"
